# Generated by Django 5.1.2 on 2024-10-29 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='SprActivitiesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('fam', models.CharField()),
                ('name', models.CharField()),
                ('otc', models.CharField()),
                ('phone', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now=True)),
                ('beautyTitle', models.CharField()),
                ('title', models.CharField()),
                ('otherTitles', models.CharField()),
                ('connect', models.CharField()),
                ('add_time', models.CharField()),
                ('spring', models.CharField(null=True)),
                ('summer', models.CharField(null=True)),
                ('autumn', models.CharField(null=True)),
                ('winter', models.CharField(null=True)),
                ('status', models.CharField(choices=[('n', 'new'), ('p', 'pending'), ('a', 'accepted'), ('r', 'rejected')], default='n')),
                ('coords_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.coords')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(null=True)),
                ('id_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.perevaladded')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.images')),
                ('pereval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.perevaladded')),
            ],
        ),
    ]
