# Generated by Django 5.1.2 on 2024-10-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_perevaladded_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='title',
            field=models.CharField(default=''),
        ),
    ]
