# Generated by Django 5.1.2 on 2024-10-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_images_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.BinaryField(default=False, editable=True),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='autumn',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='connect',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='otherTitles',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='spring',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='summer',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='winter',
            field=models.CharField(blank=True, null=True),
        ),
    ]
